# Generated by Django 4.2.4 on 2024-10-13 22:43

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpop_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', banjo.models.IntegerField(default=0)),
                ('debut', banjo.models.StringField(default='')),
                ('fandom_name', banjo.models.StringField(default='')),
                ('fandom_colour', banjo.models.StringField(default='')),
                ('likes', banjo.models.IntegerField(default=0)),
                ('popularity', banjo.models.FloatField(default=0.0)),
                ('comment', banjo.models.StringField(default='')),
                ('views', banjo.models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
