# Generated by Django 5.1.2 on 2024-10-15 06:53

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kpop_profile_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpop_profile',
            name='company',
            field=banjo.models.StringField(default=''),
        ),
    ]
