# Generated by Django 5.1.2 on 2024-10-18 00:31

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kpop_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpop_profile',
            name='artist_name',
            field=banjo.models.StringField(default=''),
        ),
    ]
